version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports: 
      - 15672:15672
      - 5672:5672
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - java-db:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    external_links:
    - db:mysql
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      PMA_HOST: db
volumes:
  java-db: