spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: admin123
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  