spring:
  datasource:
    url: jdbc:mysql://db/db
    username: root
    password: admin123
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  rabbitmq: 
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.mailtrap.io
    port: 2525
    auth: true
    username: 79e6bb7eaed7d1
    password: a7790b458fa607
    starttls:
      enable: true
      
  